[package]
name = "ct_nox"
version = "0.1.0"
authors = ["veto"]
edition = "2021"
rust-version = "1.80"
[dependencies]
clap = {version='*', features = ["cargo"]}
hex = "*"
rust-crypto = "*"
rand = "*"

